namespace WeatherData_App
{
    [default_interface]
    runtimeclass WeatherDataUserControl : Windows.UI.Xaml.Controls.UserControl
    {
        WeatherDataUserControl();
        static Windows.UI.Xaml.DependencyProperty LabelProperty{ get; };
        String Label;
    }
}
